routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PengurusanController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/laman-utama', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('laman-utama');
Route::get('/invoice', function () {
    return view('invoice');
})->middleware(['auth', 'verified'])->name('invoice');
Route::get('/quotation', function () {
    return view('quotation');
})->middleware(['auth', 'verified'])->name('quotation');

Route::get('/permohonan', function () {
    return view('permohonan');
})->middleware(['auth', 'verified'])->name('permohonan');

Route::get('/senarai-permohonan', function () {
    return view('senarai-permohonan');
})->middleware(['auth', 'verified'])->name('senarai-permohonan');

// Routes for different roles
Route::middleware(['auth', 'role:Pelulus BSM'])->group(function () {
    Route::get('/pelulus-bsm', function () {
        return 'Pelulus BSM Dashboard';
    });
});

Route::middleware(['auth', 'role:Penyemak BSM'])->group(function () {
    Route::get('/penyemak-bsm', function () {
        return 'Penyemak BSM Dashboard';
    });
});

Route::middleware(['auth', 'role:Agensi'])->group(function () {
    Route::get('/agensi', function () {
        return 'Agensi Dashboard';
    });
});

// Route::middleware(['auth', 'role:Klinik'])->group(function () {
//     Route::get('/senarai-klinik', [PengurusanController::class, 'senaraiKlinik'])->name('senarai-klinik');
//     Route::post('/store/klinik', [PengurusanController::class, 'storeKlinik'])->name('store.klinik');
//     Route::post('/update/klinik', [PengurusanController::class, 'updateKlinik'])->name('update.klinik');
//     Route::post('/delete/klinik', [PengurusanController::class, 'deleteKlinik'])->name('delete.klinik');
//     Route::get('/senarai-pengguna-klinik', [PengurusanController::class, 'senaraiPenggunaKlinik'])->name('senarai-pengguna-klinik');
//     Route::post('/store/pengguna/klinik', [PengurusanController::class, 'storePenggunaKlinik'])->name('store.klinik');
//     Route::post('/update/pengguna/klinik', [PengurusanController::class, 'updatePenggunaKlinik'])->name('update.klinik');
//     Route::post('/delete/pengguna/klinik', [PengurusanController::class, 'deletePenggunaKlinik'])->name('delete.klinik');
// });

// Route::middleware(['auth', 'role:Admin JU'])->group(function () {
//     Route::get('/pengurusan-profil-bod', [PengurusanController::class, 'senaraiBOD'])->name('pengurusan-profil-bod');
//     Route::post('/store/bod', [PengurusanController::class,'storeBOD'])->name('store.bod');
//     Route::post('/update/bod', [PengurusanController::class,'updateBOD'])->name('update.bod');
//     Route::post('/delete/bod', [PengurusanController::class,'deleteBOD'])->name('delete.bod');
//     Route::post('/store/tanggungan', [PengurusanController::class,'storeTanggungan'])->name('store.tanggungan');
//     Route::post('/update/tanggungan', [PengurusanController::class,'updateTanggungan'])->name('update.tanggungan');
//     Route::post('/delete/tanggungan', [PengurusanController::class,'deleteTanggungan'])->name('delete.tanggungan');
// });

Route::middleware(['auth', 'role:Admin JU'])->group(function () {
    Route::get('/pengurusan-profil-bod', [PengurusanController::class, 'senaraiBOD'])->name('pengurusan-profil-bod');
    Route::post('/store/bod', [PengurusanController::class,'storeBOD'])->name('store.bod');
    Route::post('/update/bod', [PengurusanController::class,'updateBOD'])->name('update.bod');
    Route::post('/delete/bod', [PengurusanController::class,'deleteBOD'])->name('delete.bod');
    Route::post('/store/tanggungan', [PengurusanController::class,'storeTanggungan'])->name('store.tanggungan');
    Route::post('/update/tanggungan', [PengurusanController::class,'updateTanggungan'])->name('update.tanggungan');
    Route::post('/delete/tanggungan', [PengurusanController::class,'deleteTanggungan'])->name('delete.tanggungan');
    Route::get('/senarai-klinik', [PengurusanController::class, 'senaraiKlinik'])->name('senarai-klinik');
    Route::post('/store/klinik', [PengurusanController::class, 'storeKlinik'])->name('store.klinik');
    Route::post('/update/klinik', [PengurusanController::class, 'updateKlinik'])->name('update.klinik');
    Route::post('/delete/klinik', [PengurusanController::class, 'deleteKlinik'])->name('delete.klinik');
    Route::get('/senarai-pengguna-klinik', [PengurusanController::class, 'senaraiPenggunaKlinik'])->name('senarai-pengguna-klinik');
    Route::post('/store/pengguna/klinik', [PengurusanController::class, 'storePenggunaKlinik'])->name('store.pengguna-klinik');
    Route::post('/update/pengguna/klinik', [PengurusanController::class, 'updatePenggunaKlinik'])->name('update.pengguna-klinik');
    Route::post('/delete/pengguna/klinik', [PengurusanController::class, 'deletePenggunaKlinik'])->name('delete.pengguna-klinik');
    Route::get('/senarai-caj-rundingan', [PengurusanController::class, 'senaraiCajRundingan'])->name('senarai-caj-rundingan');
    Route::post('/store/caj-rundingan', [PengurusanController::class, 'storeCajRundingan'])->name('store.caj-rundingan');
    Route::post('/update/caj-rundingan', [PengurusanController::class, 'updateCajRundingan'])->name('update.caj-rundingan');
    Route::post('/delete/caj-rundingan', [PengurusanController::class, 'deleteCajRundingan'])->name('delete.caj-rundingan');
    Route::get('/senarai-rawatan', [PengurusanController::class, 'senaraiRawatan'])->name('senarai-rawatan');
    Route::post('/store/rawatan', [PengurusanController::class, 'storeRawatan'])->name('store.rawatan');
    Route::post('/update/rawatan', [PengurusanController::class, 'updateRawatan'])->name('update.rawatan');
    Route::post('/delete/rawatan', [PengurusanController::class, 'deleteRawatan'])->name('delete.rawatan');
    Route::get('/senarai-ubatan', [PengurusanController::class, 'senaraiUbatan'])->name('senarai-ubatan');
    Route::post('/store/ubatan', [PengurusanController::class, 'storeUbatan'])->name('store.ubatan');
    Route::post('/update/ubatan', [PengurusanController::class, 'updateUbatan'])->name('update.ubatan');
    Route::post('/delete/ubatan', [PengurusanController::class, 'deleteUbatan'])->name('delete.ubatan');
    Route::get('/senarai-ujian-makmal', [PengurusanController::class, 'senaraiUjianMakmal'])->name('senarai-ujian-makmal');
    Route::post('/store/ujian-makmal', [PengurusanController::class, 'storeUjianMakmal'])->name('store.ujian-makmal');
    Route::post('/update/ujian-makmal', [PengurusanController::class, 'updateUjianMakmal'])->name('update.ujian-makmal');
    Route::post('/delete/ujian-makmal', [PengurusanController::class, 'deleteUjianMakmal'])->name('delete.ujian-makmal');
    Route::get('/senarai-permohonan-perubatan', [PengurusanController::class, 'senaraiPermohonanPerubatan'])->name('senarai-permohonan-perubatan');
    Route::post('/store/permohonan-perubatan', [PengurusanController::class, 'storePermohonanPerubatan'])->name('store.permohonan-perubatan');
    Route::post('/update/permohonan-perubatan', [PengurusanController::class, 'updatePermohonanPerubatan'])->name('update.permohonan-perubatan');
    Route::post('/delete/permohonan-perubatan', [PengurusanController::class, 'deletePermohonanPerubatan'])->name('delete.permohonan-perubatan');
});



Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <li aria-current="page">
          <div class="flex items-center">
            <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
            <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">Laman Utama</span>
          </div>
        </li>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="w-full p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
              <div class="flex items-center justify-between mb-4">
                  <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">Senarai Profil BOD</h5>

              </div>
          </div>
        </div>
    </div>
</x-app-layout>
<x-modal name="tambah-permohonan-perubatan" focusable maxWidth="6xl">
    <form method="post" action="{{ route('store.permohonan-perubatan') }}" class="p-6">
        @csrf
        <input type="hidden" name="application_fk_user" value="{{ Auth::user()->id }}">
        <h2 class="text-lg mb-6 font-medium text-gray-900 dark:text-gray-100">
            {{ __('Maklumat Permohonan Perubatan') }}
        </h2>
        <div class="grid gap-6 md:grid-cols-2">
            <div>
                <label for="application_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Tarikh Mohon</label>
                <!-- Display the current date in the desired format -->
                <input type="text" id="application_date" name="application_date" value="{{ date('d-m-Y') }}" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
                @error('application_date')
                    <span class="text-red-600 text-sm">{{ $message }}</span>
                @enderror
            </div>
            <div>
                <label for="application_no" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">No. Permohonan</label>
                <input type="text" id="application_no" name="application_no" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
                @error('application_no')
                    <span class="text-red-600 text-sm">{{ $message }}</span>
                @enderror
            </div>
            <div>
                @php
                    $klinik = App\Models\Klinik::all();
                @endphp
                <label for="application_fk_clinic" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Pilih Klinik</label>
                <select id="application_fk_clinic" name="application_fk_clinic" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
                    <option selected>Pilih Klinik</option>
                    @foreach($klinik as $item)
                        <option value="{{ $item->id }}">{{ $item->clinic_name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="mt-8 relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400" id="ujianTable">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">Bill</th>
                        <th scope="col" class="px-6 py-3">Jenis</th>
                        <th scope="col" class="px-6 py-3">Perkara</th>
                        <th scope="col" class="px-6 py-3">Harga (RM)</th>
                        <th scope="col" class="px-6 py-3"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700" id="row1">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">1</th>
                        <td class="px-6 py-4">
                            <select name="application_type[]" class="w-full bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
                                <option value="" disabled selected>Pilih Perubatan</option>
                                <option value="Caj Rundingan">Caj Rundingan</option>
                                <option value="Rawatan">Rawatan</option>
                                <option value="Ubatan">Ubatan</option>
                                <option value="Ujian Makmal">Ujian Makmal</option>
                            </select>
                        </td>
                        <td class="px-6 py-4">
                            <input type="text" name="application_item[]" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
                        </td>
                        <td class="px-6 py-4">
                            <input type="number" name="application_amaun[]" step="0.01" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
                        </td>
                        <td class="px-6 py-4">
                            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline" onclick="removeRow(this)">
                                <svg class="w-6 h-6 text-red-700 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                    <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm7.707-3.707a1 1 0 0 0-1.414 1.414L10.586 12l-2.293 2.293a1 1 0 1 0 1.414 1.414L12 13.414l2.293 2.293a1 1 0 0 0 1.414-1.414L13.414 12l2.293-2.293a1 1 0 0 0-1.414-1.414L12 10.586 9.707 8.293Z" clip-rule="evenodd"/>
                                </svg>
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="mt-4 ms-4 flex justify-start">
            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline" onclick="addRow()">
                <svg class="w-6 h-6 text-blue-700 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                    <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4.243a1 1 0 1 0-2 0V11H7.757a1 1 0 1 0 0 2H11v3.243a1 1 0 1 0 2 0V13h3.243a1 1 0 1 0 0-2H13V7.757Z" clip-rule="evenodd"/>
                </svg>
            </a>
        </div>
        <div class="mt-6 flex justify-end">
            <x-secondary-button x-on:click="$dispatch('close')">
                {{ __('Tutup') }}
            </x-secondary-button>

            <x-primary-button class="ms-3">
                {{ __('Simpan') }}
            </x-primary-button>
        </div>
    </form>

    <script>
        function addRow() {
            const table = document.getElementById('ujianTable').getElementsByTagName('tbody')[0];
            const rowCount = table.rows.length;
            const row = table.insertRow(rowCount);
            row.innerHTML = `
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">${rowCount + 1}</th>
                <td class="px-6 py-4">
                    <select name="application_type[]" class="w-full bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
                        <option value="" disabled selected>Pilih Perubatan</option>
                        <option value="Caj Rundingan">Caj Rundingan</option>
                        <option value="Rawatan">Rawatan</option>
                        <option value="Ubatan">Ubatan</option>
                        <option value="Ujian Makmal">Ujian Makmal</option>
                    </select>
                </td>
                <td class="px-6 py-4">
                    <input type="text" name="application_item[]" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
                </td>
                <td class="px-6 py-4">
                    <input type="number" name="application_amaun[]" step="0.01" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
                </td>
                <td class="px-6 py-4">
                    <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline" onclick="removeRow(this)">
                        <svg class="w-6 h-6 text-red-700 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                            <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm7.707-3.707a1 1 0 0 0-1.414 1.414L10.586 12l-2.293 2.293a1 1 0 1 0 1.414 1.414L12 13.414l2.293 2.293a1 1 0 0 0 1.414-1.414L13.414 12l2.293-2.293a1 1 0 0 0-1.414-1.414L12 10.586 9.707 8.293Z" clip-rule="evenodd"/>
                        </svg>
                    </a>
                </td>
            `;
        }

        function removeRow(element) {
            const row = element.parentNode.parentNode;
            row.parentNode.removeChild(row);
            updateRowNumbers();
        }

        function updateRowNumbers() {
            const rows = document.querySelectorAll('#ujianTable tbody tr');
            rows.forEach((row, index) => {
                row.querySelector('th').textContent = index + 1;
            });
        }
    </script>
</x-modal>

resources/views/invoice.blade.php
<x-app-layout>
    <x-slot name="header">
        <li aria-current="page">
          <div class="flex items-center">
            <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
            <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">Invoice</span>
          </div>
        </li>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="sm:w-11/12 lg:w-3/4 mx-auto">
                <!-- Card -->
                <div class="flex flex-col p-4 sm:p-10 bg-white shadow-md rounded-xl dark:bg-neutral-800">
                  <!-- Grid -->
                  <div class="flex justify-between">
                    <div>
                      <h1 class="mt-2 text-lg md:text-xl font-semibold text-blue-600 dark:text-white">Muhammad Tantowi Isnar.</h1>
                    </div>
                    <!-- Col -->

                    <div class="text-end">
                      <h2 class="text-2xl md:text-3xl font-semibold text-gray-800 dark:text-neutral-200">Invoice #</h2>
                      <span class="mt-1 block text-gray-500 dark:text-neutral-500">23-005</span>

                      <address class="mt-4 not-italic text-gray-800 dark:text-neutral-200">
                        No.7062 Taman Semarak<br>
                        Lorong 31 Jalan Kuhara<br>
                        Tawau, Sabah 91000<br>
                      </address>
                    </div>
                    <!-- Col -->
                  </div>
                  <!-- End Grid -->

                  <!-- Grid -->
                  <div class="mt-8 grid sm:grid-cols-2 gap-3">
                    <div>
                      <h3 class="text-lg font-semibold text-gray-800 dark:text-neutral-200">Bill to:</h3>
                      <h3 class="text-lg font-semibold text-gray-800 dark:text-neutral-200">3F Resources Sdn Bhd</h3>
                      <address class="mt-2 not-italic text-gray-500 dark:text-neutral-500">
                        No. 78, Jalan Wangsa Delima 6,<br>
                        Pusat Bandar Wangsa Maju (KLSC),<br>
                        53300 Kuala Lumpur<br>
                      </address>
                    </div>
                    <!-- Col -->

                    <div class="sm:text-end space-y-2">
                      <!-- Grid -->
                      <div class="grid grid-cols-2 sm:grid-cols-1 gap-3 sm:gap-2">
                        <dl class="grid sm:grid-cols-5 gap-x-3">
                          <dt class="col-span-3 font-semibold text-gray-800 dark:text-neutral-200">Invoice date:</dt>
                          <dd class="col-span-2 text-gray-500 dark:text-neutral-500">07/05/2024</dd>
                        </dl>
                        <dl class="grid sm:grid-cols-5 gap-x-3">
                          <dt class="col-span-3 font-semibold text-gray-800 dark:text-neutral-200">Purchase Order:</dt>
                          <dd class="col-span-2 text-gray-500 dark:text-neutral-500">3F/PO/859/24-012</dd>
                        </dl>
                      </div>
                      <!-- End Grid -->
                    </div>
                    <!-- Col -->
                  </div>
                  <!-- End Grid -->

                  <!-- Table -->
                  <div class="mt-6">
                    <div class="border border-gray-200 p-4 rounded-lg space-y-4 dark:border-neutral-700">
                      <div class="hidden sm:grid sm:grid-cols-5">
                        <div class="sm:col-span-3 text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Item</div>
                        <div class="text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Qty</div>
                        <div class="text-end text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Amount</div>
                      </div>

                      <div class="hidden sm:block border-b border-gray-200 dark:border-neutral-700"></div>

                      <div class="grid grid-cols-3 sm:grid-cols-5 gap-2">
                        <div class="col-span-full sm:col-span-3">
                          <h5 class="sm:hidden text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Item</h5>
                          <p class="font-medium text-gray-800 dark:text-neutral-200">Development of e-Klinik PPJ, June 2024</p>
                        </div>
                        <div>
                          <h5 class="sm:hidden text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Qty</h5>
                          <p class="text-gray-800 dark:text-neutral-200">1</p>
                        </div>
                        <div>
                          <h5 class="sm:hidden text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Amount</h5>
                          <p class="sm:text-end text-gray-800 dark:text-neutral-200">RM 4000,00</p>
                        </div>
                      </div>

                      <div class="sm:hidden border-b border-gray-200 dark:border-neutral-700"></div>

                    </div>
                  </div>
                  <!-- End Table -->

                  <!-- Flex -->
                  <div class="mt-8 flex sm:justify-end">
                    <div class="w-full max-w-2xl sm:text-end space-y-2">
                      <!-- Grid -->
                      <div class="grid grid-cols-2 sm:grid-cols-1 gap-3 sm:gap-2">
                        <dl class="grid sm:grid-cols-5 gap-x-3">
                          <dt class="col-span-3 font-semibold text-gray-800 dark:text-neutral-200">Total:</dt>
                          <dd class="col-span-2 text-gray-500 dark:text-neutral-500">RM 4000,00</dd>
                        </dl>
                      </div>
                      <!-- End Grid -->
                    </div>
                  </div>
                  <!-- End Flex -->

                  <div class="mt-8 sm:mt-12">
                    <h4 class="text-lg font-semibold text-gray-800 dark:text-neutral-200">Thank you!</h4>
                    <div class="mt-2">
                      <p class="block text-sm font-medium text-gray-800 dark:text-neutral-200">CIMB Bank</p>
                      <p class="block text-sm font-medium text-gray-800 dark:text-neutral-200">7074921241</p>
                    </div>
                  </div>

                  <p class="mt-5 text-sm text-gray-500 dark:text-neutral-500">© 2024 IbnIsnar.</p>
                </div>
                <!-- End Card -->

                <!-- Buttons -->
                <div class="mt-6 flex justify-end gap-x-3">
                  <a class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-lg border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-neutral-800 dark:hover:bg-neutral-800 dark:border-neutral-700 dark:text-neutral-400 dark:hover:text-white dark:focus:ring-offset-gray-800" href="#">
                  <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>
                    Invoice PDF
                  </a>
                  <a class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none" href="#">
                    <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect width="12" height="8" x="6" y="14"/></svg>
                    Print
                  </a>
                </div>
                <!-- End Buttons -->
            </div>
        </div>
    </div>
</x-app-layout>